language: node_js

node_js:
  - "10"
  - "9"

# blocklist
# branches:
#   except:
#   - legacy
#   - experimental

# safelist - Build all branches
branches:
  only:
  - gh-pages
  - /.*/

before_script:
  - npm install

# before_install:
# - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
# - git lfs pull

script:
  - npm run test

deploy:
  provider: heroku
  api_key: 70b830ec-8aa6-4b47-b522-900909730350
  on:
    branch: master




